micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: changeThisSecretToALongSecureString
  credentials:
    users:
      smith: smith123
      scott: scott123
      piomin: piomin123
      test: test123
      my-user: secret
    roles:
      smith: ADMIN
      scott: VIEW
      piomin: VIEW
      test: ADMIN
hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hello from Service!"
  config:
    greeting:
      de: "Hallo"
      en: "Hello"
netty:
  default:
    allocator:
      max-order: 3
# JSON Settings
jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDateWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    failOnUnknownProperties: false
  generator:
    writeNumbersAsStrings: false
    writeBigDecimalAsPlain: false

flyway:
  datasources:
    default:
      enabled: true
      clean-schema: true
      schemas: mn
      default-schema: mn
datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/mn-stock-broker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
# micronaut-data-jpa
jpa:
    packages-to-json:
      - "com.example.broker.persistence.jpa"
    properties:
      hibernate:
        show_sql: false








